const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
function page(){const nodes=new Map();const get=id=>{if(!nodes.has(id))nodes.set(id,{textContent:''});return nodes.get(id)};const ctx={document:{getElementById:get},window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../public/js/ml-performance.js'),'utf8'),ctx);return {get,update:ctx.window.pfimsPerformance.update}}
test('uses active any-overrun results rather than candidate reports',()=>{const p=page();p.update({mean_absolute_percentage_error:5.97,overrun_detection:{any_overrun:{precision:80,recall:90,f1_score:85,classification_accuracy:88}},candidate_evaluations:{reports:{presentation_progress:{evaluation:{precision:1}}}}});assert.equal(p.get('metricPrecision').textContent,'80.00%');assert.equal(p.get('metricOverrunAccuracy').textContent,'88.00%');assert.equal(p.get('metricMAPE').textContent,'5.97%');assert.match(p.get('performanceScope').textContent,/active forecasting model/)});
test('does not reuse legacy above-5-percent accuracy for any overrun, clears stale scores',()=>{const p=page();p.update({precision:null,recall:null,f1_score:null,overrun_classification_accuracy:100});assert.equal(p.get('metricRecall').textContent,'Unavailable');assert.equal(p.get('metricOverrunAccuracy').textContent,'Unavailable');p.update({});assert.equal(p.get('metricOverrunAccuracy').textContent,'Unavailable')});
test('shows the served algorithm and recovery state without selecting candidate metrics',()=>{const p=page();p.update({model_type:'support_vector_regression_rbf',model_recovery_source:'previous',candidate_evaluations:{reports:{planning:{model_type:'ridge_linear_regression'}}}});assert.match(p.get('performanceAlgorithm').textContent,/Support vector regression \(SVR\)/);assert.match(p.get('performanceAlgorithm').textContent,/previous verified model/);p.update({model_type:'least_squares_linear_regression',model_recovery_source:'active'});assert.equal(p.get('performanceAlgorithm').textContent,'Active cost model: Linear regression.')});

test('shows rejected optimization separately, warns on scarce overruns and clears stale results',()=>{const p=page();p.update({mean_absolute_error:50000,overrun_detection:{any_overrun:{actual_overruns:1,classification_accuracy:90,recall:0}},latest_optimization:{algorithm:'ridge_linear_regression',evaluation:{mean_absolute_error:180000},detector_evaluation:{recall:0},cost_failed_requirements:['agreed_mae_tolerance','fresh_independent_holdout'],training_counts:{database_projects:38,dummy_projects_used:19,dummy_projects_available:1000,test_database_projects:10}}});assert.match(p.get('metricMAE').textContent,/50,000/);assert.match(p.get('performanceCandidateResults').textContent,/180,000/);assert.match(p.get('performanceCandidateStatus').textContent,/Not activated/);assert.match(p.get('performanceCandidateStatus').textContent,/fresh independent/);assert.match(p.get('performanceReliability').textContent,/Only 1 actual overruns/);assert.match(p.get('performanceCandidateTraining').textContent,/38 database projects \+ 19 ingested/);p.update({});assert.equal(p.get('performanceCandidateResults').textContent,'');assert.match(p.get('performanceCandidateStatus').textContent,/No optimization/)});

test('reports ingested projects used rather than all available projects as training',()=>{const p=page();p.update({training_projects:57,augmentation:{database_training_project_ids:Array(38).fill(1),database_test_project_ids:Array(10).fill(2),dummy_projects:1000}});assert.match(p.get('performanceValidation').textContent,/38 database projects \+ 19 ingested projects used/);assert.match(p.get('performanceValidation').textContent,/1000 available/)});

test('explains the ingested data rules and 80/20 split without changing active scores',()=>{const p=page();p.update({mean_absolute_error:12345,latest_optimization:{algorithm:'ridge_linear_regression',training_counts:{database_test_ratio:.20,ingested_expenses_per_project:300,ingested_inventory_transactions_per_project:500,ingested_data_method:'rule_based_construction_ledgers_v1',ingested_data_year_range:[2019,2026]}}});assert.match(p.get('performanceCandidateTraining').textContent,/2019–2026/);assert.match(p.get('performanceCandidateTraining').textContent,/at most seven months/);assert.match(p.get('performanceCandidateTraining').textContent,/300 expenses and 500 inventory transactions/);assert.match(p.get('performanceCandidateTraining').textContent,/80% for training, newest 20% for testing/);assert.doesNotMatch(p.get('performanceCandidateTraining').textContent,/dummy/);assert.match(p.get('metricMAE').textContent,/12,345/)});

test('explains median-relative MAE and preserves unavailable legacy references',()=>{const p=page();p.update({mean_absolute_error:90000,mae_target:{reference_pesos:3000000,actual_percent:3,maximum_pesos:150000,stretch_pesos:60000}});assert.match(p.get('performanceMAETarget').textContent,/3.00%/);assert.match(p.get('performanceMAETarget').textContent,/150,000/);assert.match(p.get('performanceMAETarget').textContent,/60,000/);p.update({mean_absolute_error:90000});assert.match(p.get('performanceMAETarget').textContent,/not saved/);assert.doesNotMatch(p.get('performanceMAETarget').textContent,/150,000/)});
