const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
test('omits removed notes while preserving metrics, test counts and candidate activation status',()=>{
const p=page();const metrics={prediction_strategy:'planning_spending_model',development_activation:{mode:'explicit_user_requested_development'},augmentation:{},mean_absolute_error:101581.57,mae_target:{reference_pesos:1062498.56,actual_percent:9.56,maximum_pesos:159374.78,stretch_pesos:106249.86},overrun_detection:{any_overrun:{classification_accuracy:100,actual_overruns:2,evaluated_observations:17,classification_counts:{tp:2,fn:0,fp:0,tn:15}}},latest_optimization:{algorithm:'ridge_linear_regression',prediction_strategy:'planning_spending_model',cost_failed_requirements:['fresh_independent_holdout'],feature_names:Array(16).fill('budget'),evaluation:{monitoring_segments:{by_elapsed_stage:{early:{mean_absolute_error:120000}}}},detector_evaluation:{actual_overruns:2},training_counts:{}}};
p.update(metrics);const detailIds=['performanceScope','performanceMAETarget','performanceCandidateStatus','performanceCandidateResults','performanceCandidateTraining'];const text=detailIds.map(id=>p.get(id).textContent).join(' ');
assert.doesNotMatch(text,/Activated at your request|development use|independent company validation remains pending|Errors below 10%|active metrics above are unchanged|These checkpoints measure|preliminary|Physical progress is excluded|Historical plans and valuations/);
assert.match(p.get('metricMAE').textContent,/101,581.57/);assert.equal(p.get('metricOverrunAccuracy').textContent,'100.00%');assert.match(p.get('performanceCounts').textContent,/2 actual overruns across 17/);assert.match(p.get('performanceCandidateStatus').textContent,/Not activated: a fresh independent/);
metrics.latest_optimization.active_model_changed=true;p.update(metrics);assert.doesNotMatch(p.get('performanceCandidateStatus').textContent,/Activated at your request|development use/);assert.match(p.get('performanceCandidateStatus').textContent,/now active/);
});
test('renders facts and feature chips safely, preserving decimal values and clearing stale content',()=>{
class Node { constructor(){this.children=[];this.value=''} get textContent(){return this.children.length?this.children.map(n=>n.textContent).join(' '):this.value} set textContent(value){this.children=[];this.value=String(value)} appendChild(node){this.children.push(node)} replaceChildren(...nodes){this.children=nodes;this.value=''} }
const nodes=new Map();const get=id=>{if(!nodes.has(id))nodes.set(id,new Node());return nodes.get(id)};
const ctx={document:{getElementById:get,createElement:()=>new Node()},window:{}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../public/js/ml-performance.js'),'utf8'),ctx);
ctx.window.pfimsPerformance.update({augmentation:{},development_activation:{},feature_set:{selected_feature_names:['budget','<unsafe>']},budget_baseline_comparison:{model_evaluation:{mean_absolute_percentage_error:5.25},baseline_evaluation:{mean_absolute_percentage_error:13.87}}});
assert.equal(get('performanceScope').children[0].className,'performance-facts');assert.equal(get('performanceScope').children[0].children.length,2);assert.equal(get('performanceFeatures').children[0].className,'performance-chips');assert.equal(get('performanceFeatures').children[0].children[1].textContent,'<unsafe>');assert.match(get('performanceComparison').textContent,/5.25%/);
ctx.window.pfimsPerformance.update({});assert.doesNotMatch(get('performanceFeatures').textContent,/<unsafe>/);assert.doesNotMatch(get('performanceScope').textContent,/Activated at your request/);
});
test('compares model and budget errors from the same latest project checkpoints',()=>{const p=page();p.update({prediction_strategy:'planning_spending_model',mean_absolute_percentage_error:7.05,budget_baseline_comparison:{model_evaluation:{mean_absolute_percentage_error:5},baseline_evaluation:{mean_absolute_percentage_error:13.87}}});assert.match(p.get('performanceComparison').textContent,/5.00%/);assert.match(p.get('performanceComparison').textContent,/13.87%/);assert.doesNotMatch(p.get('performanceComparison').textContent,/7.05%/);assert.match(p.get('performanceComparison').textContent,/one latest checkpoint per test project/)});
function page(){const nodes=new Map();const get=id=>{if(!nodes.has(id))nodes.set(id,{textContent:''});return nodes.get(id)};const ctx={document:{getElementById:get},window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../public/js/ml-performance.js'),'utf8'),ctx);return {get,update:ctx.window.pfimsPerformance.update}}
test('uses active any-overrun results rather than candidate reports',()=>{const p=page();p.update({mean_absolute_percentage_error:5.97,overrun_detection:{any_overrun:{precision:80,recall:90,f1_score:85,classification_accuracy:88}},candidate_evaluations:{reports:{presentation_progress:{evaluation:{precision:1}}}}});assert.equal(p.get('metricPrecision').textContent,'80.00%');assert.equal(p.get('metricOverrunAccuracy').textContent,'88.00%');assert.equal(p.get('metricMAPE').textContent,'5.97%');assert.match(p.get('performanceScope').textContent,/active forecasting model/)});
test('does not reuse legacy above-5-percent accuracy for any overrun, clears stale scores',()=>{const p=page();p.update({precision:null,recall:null,f1_score:null,overrun_classification_accuracy:100});assert.equal(p.get('metricRecall').textContent,'Unavailable');assert.equal(p.get('metricOverrunAccuracy').textContent,'Unavailable');p.update({});assert.equal(p.get('metricOverrunAccuracy').textContent,'Unavailable')});
test('shows the served algorithm and recovery state without selecting candidate metrics',()=>{const p=page();p.update({model_type:'support_vector_regression_rbf',model_recovery_source:'previous',candidate_evaluations:{reports:{planning:{model_type:'ridge_linear_regression'}}}});assert.match(p.get('performanceAlgorithm').textContent,/Support vector regression \(SVR\)/);assert.match(p.get('performanceAlgorithm').textContent,/previous verified model/);p.update({model_type:'least_squares_linear_regression',model_recovery_source:'active'});assert.equal(p.get('performanceAlgorithm').textContent,'Active cost model: Linear regression.')});

test('shows rejected optimization separately, preserves detection scores and clears stale results',()=>{const p=page();p.update({mean_absolute_error:50000,overrun_detection:{any_overrun:{actual_overruns:1,classification_accuracy:90,recall:0}},latest_optimization:{algorithm:'ridge_linear_regression',evaluation:{mean_absolute_error:180000},detector_evaluation:{recall:0},cost_failed_requirements:['agreed_mae_tolerance','fresh_independent_holdout'],training_counts:{database_projects:38,dummy_projects_used:19,dummy_projects_available:1000,test_database_projects:10}}});assert.match(p.get('metricMAE').textContent,/50,000/);assert.match(p.get('performanceCandidateResults').textContent,/180,000/);assert.match(p.get('performanceCandidateStatus').textContent,/Not activated/);assert.match(p.get('performanceCandidateStatus').textContent,/fresh independent/);assert.match(p.get('metricOverrunAccuracy').textContent,/90.00%/);assert.match(p.get('performanceCandidateTraining').textContent,/38 database projects \+ 19 ingested/);p.update({});assert.equal(p.get('performanceCandidateResults').textContent,'');assert.match(p.get('performanceCandidateStatus').textContent,/No optimization/)});

test('reports ingested projects used rather than all available projects as training',()=>{const p=page();p.update({training_projects:57,augmentation:{database_training_project_ids:Array(38).fill(1),database_test_project_ids:Array(10).fill(2),dummy_projects:1000}});assert.match(p.get('performanceValidation').textContent,/38 database projects \+ 19 ingested projects used/);assert.match(p.get('performanceValidation').textContent,/1000 available/)});

test('explains the ingested data rules and 80/20 split without changing active scores',()=>{const p=page();p.update({mean_absolute_error:12345,latest_optimization:{algorithm:'ridge_linear_regression',training_counts:{database_test_ratio:.20,ingested_expenses_per_project:300,ingested_inventory_transactions_per_project:500,ingested_data_method:'rule_based_construction_ledgers_v1',ingested_data_year_range:[2019,2026]}}});assert.match(p.get('performanceCandidateTraining').textContent,/2019–2026/);assert.match(p.get('performanceCandidateTraining').textContent,/at most seven months/);assert.match(p.get('performanceCandidateTraining').textContent,/300 expenses and 500 inventory transactions/);assert.match(p.get('performanceCandidateTraining').textContent,/80% for training, newest 20% for testing/);assert.doesNotMatch(p.get('performanceCandidateTraining').textContent,/dummy/);assert.match(p.get('metricMAE').textContent,/12,345/)});

test('explains median-relative MAE and preserves unavailable legacy references',()=>{const p=page();p.update({mean_absolute_error:90000,mae_target:{reference_pesos:3000000,actual_percent:3,maximum_pesos:450000,stretch_pesos:300000}});assert.match(p.get('performanceMAETarget').textContent,/3.00%/);assert.match(p.get('performanceMAETarget').textContent,/450,000/);assert.match(p.get('performanceMAETarget').textContent,/300,000/);p.update({mean_absolute_error:90000});assert.match(p.get('performanceMAETarget').textContent,/not saved/);assert.doesNotMatch(p.get('performanceMAETarget').textContent,/450,000/)});

test('explains record-date planning and spending, stage and project metrics without replacing active results',()=>{const p=page();p.update({prediction_strategy:'progress_snapshot_model',mean_absolute_error:50000,latest_optimization:{algorithm:'support_vector_regression_rbf',prediction_strategy:'planning_spending_model',feature_names:Array(16).fill('budget'),data_audit:{eligible_projects:84,observations:252,excluded_projects:{1:'invalid'},budget_fallback_observations:252},evaluation:{mean_absolute_error:101581,latest_observation_per_project:{mean_absolute_error:68070,mean_absolute_percentage_error:5,mae_target:{actual_percent:6.4}},monitoring_segments:{by_elapsed_stage:{early:{mean_absolute_error:120000},late:{mean_absolute_error:68070}}}},detector_evaluation:{actual_overruns:2,recall:100}}});assert.match(p.get('metricMAE').textContent,/50,000/);assert.match(p.get('performanceStatus').textContent,/progress-based/);assert.match(p.get('performanceCandidateTraining').textContent,/all 16 shared inputs/);assert.match(p.get('performanceCandidateTraining').textContent,/expense and withdrawal dates/);assert.doesNotMatch(p.get('performanceCandidateTraining').textContent,/Physical progress is excluded/);assert.match(p.get('performanceCandidateResults').textContent,/activation check/);assert.match(p.get('performanceCandidateResults').textContent,/68,070/);assert.doesNotMatch(p.get('performanceCandidateResults').textContent,/preliminary/)});

test('shows the activated planning and spending model with independent detector counts and honest scope',()=>{const p=page();p.update({prediction_strategy:'planning_spending_model',development_activation:{mode:'explicit_user_requested_development'},augmentation:{},overrun_detector_source:'independent_classifier',overrun_detector_evaluation_unit:'latest_observation_per_project',overrun_detection:{any_overrun:{classification_accuracy:100,precision:100,recall:100,f1_score:100,actual_overruns:2,evaluated_observations:17,classification_counts:{tp:2,fn:0,fp:0,tn:15}}},latest_optimization:{active_model_changed:true,algorithm:'support_vector_regression_rbf'}});assert.match(p.get('performanceStatus').textContent,/planning and spending/);assert.match(p.get('performanceCandidateStatus').textContent,/now active/);assert.doesNotMatch(p.get('performanceCandidateStatus').textContent,/Not activated/);assert.doesNotMatch(p.get('performanceScope').textContent,/Activated at your request|independent company validation remains pending/);assert.match(p.get('performanceCounts').textContent,/17 test projects/);assert.equal(p.get('metricOverrunAccuracy').textContent,'100.00%')});
