<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class InsertReports extends Seeder
{
    public function run()
    {
        // Get user IDs
        $adminUser = DB::table('users')->where('email', 'admin@gmail.com')->first();
        $accountingUser = DB::table('users')->where('email', 'acc@gmail.com')->first();
        $operationsUser = DB::table('users')->where('email', 'ops@gmail.com')->first();

        $adminId = $adminUser ? $adminUser->id : 1;
        $accountingId = $accountingUser ? $accountingUser->id : 1;
        $operationsId = $operationsUser ? $operationsUser->id : 1;

        $reports = [
            // Admin Reports
            [
                'report_id' => 'RPT-001',
                'title' => 'System Health Report - Q2 2026',
                'type' => 'other',
                'role' => 'admin',
                'description' => 'Comprehensive system performance and uptime report',
                'file_name' => 'system_health_q2_2026.pdf',
                'file_path' => 'reports/admin/system_health_q2_2026.pdf',
                'file_size' => 2457600,
                'date_uploaded' => '2026-06-30',
                'uploaded_by' => 'Admin User',
                'status' => 'Completed',
                'user_id' => $adminId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'report_id' => 'RPT-002',
                'title' => 'User Activity Report - June 2026',
                'type' => 'other',
                'role' => 'admin',
                'description' => 'User activity log and session analytics',
                'file_name' => 'user_activity_jun2026.xlsx',
                'file_path' => 'reports/admin/user_activity_jun2026.xlsx',
                'file_size' => 1024000,
                'date_uploaded' => '2026-06-29',
                'uploaded_by' => 'Admin User',
                'status' => 'Completed',
                'user_id' => $adminId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'report_id' => 'RPT-003',
                'title' => 'Security Audit Report',
                'type' => 'other',
                'role' => 'admin',
                'description' => 'Monthly security audit and vulnerability assessment',
                'file_name' => 'security_audit_jun2026.pdf',
                'file_path' => 'reports/admin/security_audit_jun2026.pdf',
                'file_size' => 3072000,
                'date_uploaded' => '2026-06-28',
                'uploaded_by' => 'Admin User',
                'status' => 'Completed',
                'user_id' => $adminId,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Accounting Reports
            [
                'report_id' => 'RPT-004',
                'title' => 'Monthly Financial Summary - June 2026',
                'type' => 'finance',
                'role' => 'accounting',
                'description' => 'Comprehensive financial summary including revenue and expenses',
                'file_name' => 'financial_summary_jun2026.xlsx',
                'file_path' => 'reports/accounting/financial_summary_jun2026.xlsx',
                'file_size' => 1536000,
                'date_uploaded' => '2026-06-30',
                'uploaded_by' => 'Accounting Team',
                'status' => 'Completed',
                'user_id' => $accountingId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'report_id' => 'RPT-005',
                'title' => 'Annual Budget Projection 2027',
                'type' => 'budget',
                'role' => 'accounting',
                'description' => '2027 annual budget projection with departmental allocations',
                'file_name' => 'annual_budget_2027.pdf',
                'file_path' => 'reports/accounting/annual_budget_2027.pdf',
                'file_size' => 4096000,
                'date_uploaded' => '2026-06-27',
                'uploaded_by' => 'Accounting Team',
                'status' => 'Pending',
                'user_id' => $accountingId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'report_id' => 'RPT-006',
                'title' => 'Expense Analysis - Q2 2026',
                'type' => 'expense',
                'role' => 'accounting',
                'description' => 'Detailed expense analysis by category and project',
                'file_name' => 'expense_analysis_q2_2026.xlsx',
                'file_path' => 'reports/accounting/expense_analysis_q2_2026.xlsx',
                'file_size' => 2048000,
                'date_uploaded' => '2026-06-25',
                'uploaded_by' => 'Accounting Team',
                'status' => 'Completed',
                'user_id' => $accountingId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'report_id' => 'RPT-007',
                'title' => 'Labor Cost Report - June 2026',
                'type' => 'expense',
                'role' => 'accounting',
                'description' => 'Monthly labor cost breakdown and analysis',
                'file_name' => 'labor_cost_report_jun2026.csv',
                'file_path' => 'reports/accounting/labor_cost_report_jun2026.csv',
                'file_size' => 512000,
                'date_uploaded' => '2026-06-28',
                'uploaded_by' => 'Accounting Team',
                'status' => 'Completed',
                'user_id' => $accountingId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'report_id' => 'RPT-008',
                'title' => 'Material Cost Analysis',
                'type' => 'budget',
                'role' => 'accounting',
                'description' => 'Material cost analysis with supplier comparison',
                'file_name' => 'material_cost_analysis.xlsx',
                'file_path' => 'reports/accounting/material_cost_analysis.xlsx',
                'file_size' => 1024000,
                'date_uploaded' => '2026-06-24',
                'uploaded_by' => 'Accounting Team',
                'status' => 'In Progress',
                'user_id' => $accountingId,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Operations Reports
            [
                'report_id' => 'RPT-009',
                'title' => 'Project Completion Report - Q2 2026',
                'type' => 'project',
                'role' => 'operations',
                'description' => 'Summary of all completed projects in Q2 2026',
                'file_name' => 'project_completion_q2_2026.pdf',
                'file_path' => 'reports/operations/project_completion_q2_2026.pdf',
                'file_size' => 3072000,
                'date_uploaded' => '2026-06-30',
                'uploaded_by' => 'Operations Team',
                'status' => 'Completed',
                'user_id' => $operationsId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'report_id' => 'RPT-010',
                'title' => 'Inventory Stock Report - June 2026',
                'type' => 'inventory',
                'role' => 'operations',
                'description' => 'Current inventory levels and stock movement',
                'file_name' => 'inventory_stock_jun2026.csv',
                'file_path' => 'reports/operations/inventory_stock_jun2026.csv',
                'file_size' => 2048000,
                'date_uploaded' => '2026-06-29',
                'uploaded_by' => 'Operations Team',
                'status' => 'In Progress',
                'user_id' => $operationsId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'report_id' => 'RPT-011',
                'title' => 'Workforce Productivity Report',
                'type' => 'workforce',
                'role' => 'operations',
                'description' => 'Workforce productivity and efficiency metrics',
                'file_name' => 'workforce_productivity_jun2026.xlsx',
                'file_path' => 'reports/operations/workforce_productivity_jun2026.xlsx',
                'file_size' => 1536000,
                'date_uploaded' => '2026-06-28',
                'uploaded_by' => 'Operations Team',
                'status' => 'Completed',
                'user_id' => $operationsId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'report_id' => 'RPT-012',
                'title' => 'Equipment Utilization Report',
                'type' => 'inventory',
                'role' => 'operations',
                'description' => 'Equipment usage and maintenance schedule',
                'file_name' => 'equipment_utilization_q2_2026.pdf',
                'file_path' => 'reports/operations/equipment_utilization_q2_2026.pdf',
                'file_size' => 2560000,
                'date_uploaded' => '2026-06-27',
                'uploaded_by' => 'Operations Team',
                'status' => 'Pending',
                'user_id' => $operationsId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'report_id' => 'RPT-013',
                'title' => 'Supplier Performance Report',
                'type' => 'supplier',
                'role' => 'operations',
                'description' => 'Supplier performance evaluation and comparison',
                'file_name' => 'supplier_performance_jun2026.xlsx',
                'file_path' => 'reports/operations/supplier_performance_jun2026.xlsx',
                'file_size' => 819200,
                'date_uploaded' => '2026-06-26',
                'uploaded_by' => 'Operations Team',
                'status' => 'Completed',
                'user_id' => $operationsId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'report_id' => 'RPT-014',
                'title' => 'Material Consumption Report',
                'type' => 'inventory',
                'role' => 'operations',
                'description' => 'Material consumption analysis across projects',
                'file_name' => 'material_consumption_q2_2026.xlsx',
                'file_path' => 'reports/operations/material_consumption_q2_2026.xlsx',
                'file_size' => 1280000,
                'date_uploaded' => '2026-06-25',
                'uploaded_by' => 'Operations Team',
                'status' => 'Completed',
                'user_id' => $operationsId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'report_id' => 'RPT-015',
                'title' => 'Project Timeline Variance Report',
                'type' => 'project',
                'role' => 'operations',
                'description' => 'Analysis of project timeline variances',
                'file_name' => 'timeline_variance_q2_2026.pdf',
                'file_path' => 'reports/operations/timeline_variance_q2_2026.pdf',
                'file_size' => 1843200,
                'date_uploaded' => '2026-06-24',
                'uploaded_by' => 'Operations Team',
                'status' => 'Completed',
                'user_id' => $operationsId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('reports')->insert($reports);
    }
}